# Generated by Django 4.1.7 on 2023-03-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию', max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите важность задачи', max_length=20, verbose_name='Степень важности')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название задачи', max_length=100, verbose_name='Задача')),
                ('date_from', models.DateField(help_text='Введите дату начала задачи', verbose_name='Дата начала')),
                ('date_to', models.DateField(help_text='Введите дату завершения задачи', verbose_name='Дата завершения')),
                ('completeness', models.BooleanField(default=False, help_text='Задача завершена?', verbose_name='Статус выполнения')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='todos.category', verbose_name='Категория')),
                ('importance', models.ForeignKey(help_text='выберите важность задачи', on_delete=django.db.models.deletion.CASCADE, to='todos.importance', verbose_name='Важность')),
            ],
        ),
    ]
