# Generated by Django 4.1.7 on 2023-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completeness',
            field=models.BooleanField(choices=[(False, 'не завершена'), (True, 'завершена')], default=False, help_text='Задача завершена?', verbose_name='Статус выполнения'),
        ),
    ]
